[versions]
kotlin-version = "2.2.20"
protobuf-version = "4.32.1"
protobuf-plugin-version = "0.9.5"
kotlinx-version = "0.3.6"
detekt-version = "1.23.8"
ktlint-version = "14.0.1"
tasktree-version = "4.0.1"

[libraries]
google-protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "protobuf-version" }
jetbrains-kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-version" }
google-protobuf-gradle-plugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "protobuf-plugin-version" }
jetbrains-kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-version" }
jetbrains-kotlinx-cli = { group = "org.jetbrains.kotlinx", name = "kotlinx-cli", version.ref = "kotlinx-version" }

[plugins]
google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin-version" }
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt-version" }
jlleitschuh-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-version" }
dorongold-tasktree = { id = "com.dorongold.task-tree", version.ref = "tasktree-version" }
