[versions]
protobuf-version = "4.32.1"
kotlinx-version = "0.3.6"
junit-version = "6.0.1"
kotlin-version = "2.2.20"

[libraries]
google-protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "protobuf-version" }
jetbrains-kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-version" }
jetbrains-kotlinx-cli = { group = "org.jetbrains.kotlinx", name = "kotlinx-cli", version.ref = "kotlinx-version" }
test-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-version" }
test-junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-version" }

[plugins]
google-protobuf = { id = "com.google.protobuf", version = "0.9.5" }
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
jlleitschuh-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }
dorongold-tasktree = { id = "com.dorongold.task-tree", version = "4.0.1" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
